### ISSUE TITLE
The install script doesn't copy the OpenSSL Program to c:

### ISSUE THREAD

**Issue by Weber-Frank** [jens-maus/amissl#10]
The install script doesn't copy the OpenSSL Program to c:
Sorry for the one line but nothing other to say. :-)

**Comment by Futaura** [comment]
Which OS are you installing on?

**Comment by Weber-Frank** [comment]
i use here AOS 3.9

**Comment by Futaura** [comment]
Ok. It should be installing it to AmiSSL:OpenSSL - not C:. The installer then gives the option of adding AmiSSL: to the search path. However, I have just realised this option only shows up if installing on a system without a previous version of AmiSSL installed - I have now fixed this.

**Comment by jens-maus** [comment]
@Futaura I am sorry Oliver, but is this change really require. In fact that's exactly what I disabled before the release of AmiSSLv4. Why should someone always have to always decide to add AmiSSL: to the search path if this has already been performed in a previous install? I think this just will cause confusion for people wanting to update to a newer version and thus receiving the same question over and over again.

**Comment by Futaura** [comment]
@jens-maus Sorry - I didn't realise you'd changed those lines. I see your point, but I feel the way I wrote it is the safest way. What if the user wanted to change their mind regarding the search path when updating? With how the script was, this wasn't possible. Also, if the user decides to install in a different location to the existing install, it is perhaps more reasonable to expect the new install to work, rather than do nothing because the AmiSSL: assign still points to the old install. Likewise, on OS4 the script should add the assign (if for some reason the user manually removed it from a:startup-sequence). I wrote the script that way to handle all those cases.

**Comment by Futaura** [comment]
@jens-maus  I've tweaked the install script some more. Whilst improving readability (hopefully!), I've reinstated your change that removed the path question when installing over an existing installation. However, I've also reworded the initial update/new question to make it a little clearer and the user can then choose not to do that and perform a new install. Then when asked for a dir it defaults to AmiSSL: this time and the user can accept that, which is the same as updating, but then proceeds as a new install (asks about search path and updates User-Startup. Hopefully this is an acceptable solution.

**Comment by jens-maus** [comment]
@Futaura Well, I would have to first test it to tell if this is fine now. I still, however, have the suspicion that you are asking the user too many questions for no big reason/deal. Why would you ask the user over and over again on each install if he really wants to install it to AmiSSL: if there is already an AmiSSL: path existing? This IMHO clearly points out that AMISSL has been already installed and thus should be installed there again. Why would someone suddenly chose to install it somewhere else and thus potentially risk to have to installation patches for AmiSSL?

Furthermore, I also think the same way for adding the PATH and ASSIGN calls to User-Startup? If the installer already identifies that they are there, why would the installer script ask again and again? I really don't get the tiger idea of that, I am afraid. IMHO we shouldn't bother users too much and thus would be better not asking the user too many questions about something that is clear in first place.

**Comment by Futaura** [comment]
@jens-maus  Well, the script essentially runs the same now as with the changes you made shortly before release. I think it is important to give the use a choice - you could argue that it shouldn't ask which OS to install for, as the installer defects that also. I think asking only two questions for updating is perfectly OK. Should the user wish to change their mind about the search path, they can now do so (only if they say no to an update install, so not everyone will have to answer this every time).
