### ISSUE TITLE
AmiSSL Installer documentation location

### ISSUE THREAD

**Issue by paraxenic** [jens-maus/amissl#12]
The OS4 AmiSSL installation places the OpenSSL and AmiSSL documentation in SYS:Documentation. The OS4 installer places the AmiSSL documentation in SYS:Documentation/AmiSSL. It could be very confusing for a user who finds the wrong AmiSSL documentation when AmiSSL V4 is installed on his/her system. The installer should install the AmiSSL documentation in SYS:Documentation/AmiSSL.

**Comment by jens-maus** [comment]
@Futaura Can you verify if this observation is true and if we can do something about it or is everything fine?

**Comment by Futaura** [comment]
I'll check this - I didn't have the docs installed on my system so guessed a good location. My OS4 install is  not a normal one I guess (beta updates on a OS4 install before AmiSSL was available). I'll check the 4.1 FE ISO and modify the installer if necessary.

**Comment by jens-maus** [comment]
Perfect, please note that there is an important OpenSSL 1.1.x update coming this friday, thus I have planned to release 4.1 by the weekend, if possible.

**Comment by Futaura** [comment]
Checked the OS4 ISO, and sure enough the docs should be in their own dir. Fixed.
