### ISSUE TITLE
"OpenSSL speed" command appears to be broken

### ISSUE THREAD

**Issue by Futaura** [jens-maus/amissl#14]
Running "OpenSSL speed" appears to hang on the first test. Use "OpenSSL speed mdc2" for a faster test. Same on OS4 and OS3.  Works with AmiSSL v3.

**Comment by jens-maus** [comment]
I actually already recognized that quiet a while agi but didn't find it important enough to fix it ;) but if you know where to start, go ahead.

**Comment by Futaura** [comment]
No worries - I just saw somebody mention it on Amiga.org, so thought I'd add it here so I didn't forget about it :-)

**Comment by Futaura** [comment]
Seems I actually fixed this earlier this year (disabled fork usage)
