### ISSUE TITLE
OpenSSL can't open amisslmaster.library v4

### ISSUE THREAD

**Issue by KONEY** [jens-maus/amissl#16]
I installed this version on top of a old installation.
Now both the libraries live in AmiSSL:libs/AmiSSL:   
amissl_v097g.library 
amissl_v110e.library

But OpenSSL won't find the lib:
OpenSSL> Couldn't open amisslmaster.library v4

**Comment by Futaura** [comment]
Using the installer, or manual install? And which system?

Check AmiSSL:libs/amisslmaster.library

You may need to reboot after installing.

**Comment by KONEY** [comment]
using installer on A600 + Vampire 2 and KS 3.1
What exactly should I check on the lib? Version says 3.6
Rebooted when requested by the installer.

**Comment by Futaura** [comment]
Ok. Can you run the installer again with logging switched on and post the log here?

The  amisslmaster.library version should be 4.1, but I don't understand how the installer failed to install that, but did install the other library.

**Comment by KONEY** [comment]
I was pretty sure it was 3.6 but now I went back on the Amiga to try the installer again and made a re-check just to find out it is in fact 4.1. Sorry... 
OpenSSL still claims it can't open v4 of the library.  Do you want me to try and run the installer again?

**Comment by Futaura** [comment]
No need - sounds like the installer worked fine.  Is it possible that you have another copy of amisslmaster.library installed elsewhere?  SYS:Libs perhaps?  If so, delete it.

**Comment by KONEY** [comment]
That did the trick: there was an old 3.6 library in libs:, got rid of it and now it works. Thanks!
