### ISSUE TITLE
Bug in https.c example?

### ISSUE THREAD

**Issue by softwarefailure** [jens-maus/amissl#18]
I'm new to AmiSSL and I saw the following lines in the `https.c` example:

	if (AmiSSLBase)
	{
    #if defined(__amigaos4__)
		if (IAmiSSL)
		{
			CleanupAmiSSL(TAG_DONE);
			DropInterface((struct Interface *)IAmiSSL);
			IAmiSSL = NULL;
		}
    #endif

		CloseAmiSSL();
		AmiSSLBase = NULL;
	} 

Shouldn't `CleanupAmiSSL()` be called on other platforms as well and not only on OS4? So I think the code should be like this instead:

	if (AmiSSLBase)
	{
		CleanupAmiSSL(TAG_DONE);
    #if defined(__amigaos4__)
		if (IAmiSSL)
		{
			DropInterface((struct Interface *)IAmiSSL);
			IAmiSSL = NULL;
		}
    #endif

		CloseAmiSSL();
		AmiSSLBase = NULL;
	} 

Or am I getting something wrong here?

**Comment by Futaura** [comment]
Yes, you are half right. The code was only correct for OS4 and your fix was correct for anything but OS4.

I've now committed a fix which works for all. This code was originally there, but got lost some years ago during other modifications.
