### ISSUE TITLE
Includes don't work on MorphOS

### ISSUE THREAD

**Issue by softwarefailure** [jens-maus/amissl#19]
Since AmiSSL isn't available for MorphOS yet, I thought I could just use the 68k version on MorphOS for the time being. But unfortunately, the AmiSSL includes don't seem to work on MorphOS either. The file `amissl/inline.h` triggers lots of errors when trying to compile on MorphOS. Here are just the first few lines:

```
In file included from /bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/proto/amissl.h:79,
		 from /bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/openssl/ssl.h:2,
		 from vtls/openssl.c:54:
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_SCT_pop_free':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:125: error: expected expression before 'OPENSSL_STACK'
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_SCT_set_cmp_func':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:125: error: '__fpr' undeclared (first use in this function)
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:125: error: (Each undeclared identifier is reported only once
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:125: error: for each function it appears in.)
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:125: error: expected expression before 'OPENSSL_STACK'
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_CTLOG_pop_free':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:126: error: expected expression before 'OPENSSL_STACK'
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_CTLOG_set_cmp_func':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:126: error: '__fpr' undeclared (first use in this function)
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:126: error: expected expression before 'OPENSSL_STACK'
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_X509_ALGOR_pop_free':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:127: error: expected expression before 'OPENSSL_STACK'
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h: In function 'sk_X509_ALGOR_set_cmp_func':
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:127: error: '__fpr' undeclared (first use in this function)
/bin/../lib/gcc-lib/ppc-morphos/4.4.4/../../../../ppc-morphos/include/amissl/inline.h:127: error: expected expression before 'OPENSSL_STACK'
(and lots more, all related to _pop_free and _set_cmp_func)
```

Please fix.

**Comment by Futaura** [comment]
Hang on - which compiler are you using??? You can't expect the 68k includes to work with a MorphOS target - in particular the inline.h file is unique to each target.  You need a compiler with a 68k to use the 68k includes. This doesn't just apply to AmiSSL, but every Amiga !ibrary in existence!

**Comment by softwarefailure** [comment]
I think the includes have been generated using a tool which generates includes for all Amigaoid platforms so they should also work on MorphOS which should be autodetected by the includes shipped with AmiSSL.

**Comment by Futaura** [comment]
Yes, you're right and I forgot that MorphOS uses 68k calling conventions for native library calls too. We'll have to wait for @jens-maus or @tboeckel to look into this one. It looks to me like the OS3 inline/* are broken also, in a similar way to the MorphOS ppcinline/*. For starters, none of the macro calls specify the bt parameter (only bn). This becomes a major issue when the fpr parameter should be following those, which explains some of your errors. @jens-maus must have these working for OS3 at least though.

**Comment by polluks** [comment]
I've been done a MorphOS port of https://aminet.net/package/comm/net/AmiGemini.
However it hangs at the first call of SSL_connect().

**Comment by Geitde** [comment]
Well, with recent MorphOS 3.16 there is no need for all the fuzz, since MorphOS has a shared OpenSSL3.library now containing all functions available, which should make porting and creating stuff quite easy.

**Comment by Futaura** [comment]
This is a really old issue, which was either never an issue (AmiSSL SDK not installed correctly, possibly) or fixed long ago. I've tested building an application under MorphOS with GCC (2.95.3, 4.4.5, 5.5.0 and 6.4.0) and there are no such errors and the compiled application works perfectly well.
