### ISSUE TITLE
Alternative backend (WolfSSL)

### ISSUE THREAD

**Issue by edolnx** [jens-maus/amissl#23]
Greetings! First off, thanks so much for keeping AmiSSL alive. It's nice for my Amiga to be able to use a web browser on the modern Internet still. I found the project via aminet as was pleasantly surprised to find someone is still maintaining it. In a related topic to #22 I was wondering what the future of this library looks like. My understanding is that "legacy" architectures and operating systems (including 68k, PPC, and AmigaOS) are being removed from OpenSSL after the 1.0.2. Being unaware of this project being active, I was planning on using [WolfSSL](https://github.com/wolfSSL/wolfssl) and seeing if AmiSSL could be ported to this. WolfSSL is designed for embedded systems (meaning it's a small code base), still supports 68k and PPC processors, implements modern technologies like TTLS1.2 and TLS1.3, and has an OpenSSL compatibility layer. I figured it would at least be worth opening a discussion if there was interest in collaborating on an effort to add WolfSSL to AmiSSL or if the maintainers already had other plans...

**Comment by Futaura** [comment]
AmiSSL is designed in such a way that different SSL libraries could be supported, but there are negatives and positives. WolfSSL no doubt only supports a subset of the crypto and SSL parts of OpenSSL, so OpenSSL could not be dropped completely. So, although OpenSSL is not so compact, AmiSSL is not a link library, so it is only using memory once and the code is shared by all programs that use it.

AmiSSL currently uses OpenSSL 1.1.0, which still has AltiVec optimisation, so I don't see any sign of PPC and 68k support yet. I think we currently need to concentrate on more frequent AmiSSL updates, as OpenSSL 1.1.1 is available with TLS 1.3 already. Currently, only @jens-maus is in a position to make these updates and it is a shame no other developers have jumped on board to help with this process as Jens only has so much spare time.

**Comment by edolnx** [comment]
Request retracted
