### ISSUE TITLE
Newlib libamisslauto.a fails to link with undefined reference to 'errno'

### ISSUE THREAD

**Issue by ksdhans** [jens-maus/amissl#32]
As the subject line says, attempting to use the autoinit stub with newlib results in the "undefined reference to 'errno'" linking error.

Looking at the makefile, it's likely that -mcrt=clib2 is still in the command line when compiling the autoinit stub for newlib, resulting in the linking error.

**Comment by Futaura** [comment]
Now fixed: 6b0f9ce4cef3bddfc054e4ab8b2609c93f710c6f
