### ISSUE TITLE
Openssl command fails when using the -out parameter

### ISSUE THREAD

**Issue by ksdhans** [jens-maus/amissl#33]
Running the following command:
openssl ecparam -name secp521r1 -genkey -param_enc named_curve -out "ram:key"

will fail with the following warning and error:
*** WARNING (BIO_new_fp): 5A1CE7B8 is neither stdin (5A1C8048), stdout (5A1C80B0) nor stderr (5A1C8118) in GetFileBPTR in stubs, returning NULL!
unable to write elliptic curve parameters
1415989712:error:09072007:PEM routines:PEM_write_bio:BUF lib:../../openssl/crypto/pem/pem_lib.c:658:

It works just fine without the -out parameter, but then it's writing to stdout instead of a file. 

The file itself is created, but empty.

**Comment by Futaura** [comment]
Fixed (and for many other commands also, not just ecparam)

**Comment by ckilee** [comment]
Hi,

I am facing a similar problem in my aplication, can you just let me know how could you fix this issue?
