### ISSUE TITLE
Openssl fails when generating a self-signed certificate due to missing AmiSSL:/openssl.cnf

### ISSUE THREAD

**Issue by ksdhans** [jens-maus/amissl#34]
As the subject says, the default AmiSSL installation is missing the openssl.cnf file, which means that the openssl command will fail to generate certificates. 

Here's the command line for generating a cert:
openssl req -new -x509 -key "key.pem" -days 730 -subj "/CN=localhost" -out "server.pem"

You'll get this error:
Can't open AmiSSL:/openssl.cnf for reading, No such file or directory

**Comment by ksdhans** [comment]
Actually, it still fails even if there's an openssl.cnf file in AmiSSL.

**Comment by raziel-** [comment]
Isn't that
AmiSSL:/openssl.cnf
a path error (linux and amiga path structure mixed)?

So, even if the file is available the programm can never access it (create/write/read) due to the wrong path structure...

**Comment by ksdhans** [comment]
Yes, that's an invalid path.

**Comment by kowoba** [comment]
It's not an invalid path on Amiga, it means the directory above the AmiSSL: assign, you should try putting openssl.cnf there. But this is certainly not what was intended, so still a bug.
