### ISSUE TITLE
Fix cert files for 4.4

### ISSUE THREAD

**Issue by Futaura** [jens-maus/amissl#36]
In the 4.3 release, something appears to have gone wrong with the generation of the cert files in Certs. Specifically, 5ad8a5d6.0 and b0ed035a.0 both contain a complete multi-cert bundle instead of the 2 certs they should contain.

**Comment by jens-maus** [comment]
Hi Oliver. How did you update these certs? Did you use the dedicated script for that which automatically fetches the latest official ones?

**Comment by Futaura** [comment]
Yes, I used the update_certs.sh script - no major changes, although I fixed the simple bug in the script that was causing the full ca_bundle.crt file to be included and renamed as a cert file. I'm doing all the changes on Linux for now, instead of on my OS4 system, hence I could use the script :)
