### ISSUE TITLE
Crashes when no FPU present

### ISSUE THREAD

**Issue by Futaura** [jens-maus/amissl#37]
Unfortunately, AmiSSL crashes on on 68020 or 68030 with no FPU present. This is because the library is being compiled with the `-m68020-60` option, which allows FPU instructions to be generated as `-mhard-float` becomes the default. At the very least we must explicitly specify `-msoft-float` to fix the crashes.

**Comment by QkiZMR** [comment]
It's compile option, not runtime option?

**Comment by Futaura** [comment]
Yes. This will be sorted for the next release.
