### ISSUE TITLE
Install script fails to modify user-startup on MorphOS

### ISSUE THREAD

**Issue by jPV1260** [jens-maus/amissl#41]
No lines are added to the S:user-startup file when installing AmiSSL 4.3 on MorphOS with the provided installation script.

If a user doesn't happen to have the assigns from a previous installation/version, he has to dig out the reason why AmiSSL doesn't work after a fresh install, and add them manually.

**Comment by Futaura** [comment]
Already fixed in 19961877bdd360846bf38b6584f6f00a0217a001 for next release
