### ISSUE TITLE
Optional installation of include?

### ISSUE THREAD

**Issue by polluks** [jens-maus/amissl#55]
Just save 8 MB for a non-developer.
How about a separate dev archive..?

**Comment by Futaura** [comment]
I've changed my mind on this for AmiSSL v5 - OpenSSL 3.0 has caused AmiSSL to grow in size and now that stub libraries are included, the SDK has grown too (20MB uncompressed). With the full archive being 8.5MB compressed, it is almost 40MB when uncompressed, which may pose a problem to lower end classic systems. So, AmiSSL v5 will have separate archives for OS3, OS4 and the SDK.
