### ISSUE TITLE
const const in header files

### ISSUE THREAD

**Issue by kjeacle** [jens-maus/amissl#61]
Getting compilation warnings with VBCC since 5.1. Appears to be due to:

```
% grep -lr "const const" .
./include/defines/amissl.h
./include/inline/amissl.h
./include/interfaces/amissl.h
./include/ppcinline/amissl.h
./sfd/amissl_lib.sfd
./xml/amissl.xml
```

**Comment by Futaura** [comment]
Thanks for the report - the warnings should be safe to ignore as the function with the `const const` parameter should never get used anyway in v5. I've also fixed this, so feel to update your files from https://github.com/jens-maus/amissl/tree/master/include - for VBCC, the ones of importance are:
```
inline/amissl_protos.h
interfaces/amissl.h
```

**Comment by kjeacle** [comment]
Thanks for the quick fix!
