### ISSUE TITLE
Example https Crashes on Vanilla AmigaOS v3.2 Installation on WinUAE

### ISSUE THREAD

**Issue by tygre-chingu** [jens-maus/amissl#69]
Hi and thanks for AmiSSL!
It's really great to have an up-to-date OpenSSL library for AmigaOS 👍 

I'm trying to build my own simple HTTPS client, based on the examples provided in the Examples folder. I noticed that on my vanilla AmigaOS v3.2 installation on WinUAE, the example `httpget` works (with both HTTP and HTTPS) but `https` either invites a Guru 8000 0004 or crashes WinUAE, depending on whether I enable the FPU or not. Either way, the problem seems to come from the call to `SSL_connect()`.

(`https` works well on my real Amiga with OS v3.1 running on a 68060 with MMU and FPU.)

Could it really be a problem in `https`?
How could I go about debugging and fixing this problem?

**Comment by tygre-chingu** [comment]
Ah, my bad! The problem wasn't in the example code and AmigaOS v3.2 but in the stack size: [thanks to AmigaSystem and Patrik](http://eab.abime.net/showthread.php?p=1587319), after increasing the stack size to 16384, it works fine! (And so does AmiModRadio 👍)

**Comment by Futaura** [comment]
Glad you got it sorted!

**Comment by tygre-chingu** [comment]
Thanks Futaura!
StackAttack is my friend but it can also hide bugs...
