### ISSUE TITLE
X509_INFO_free, X509_free undefined reference

### ISSUE THREAD

**Issue by boingball** [jens-maus/amissl#71]
I've built a test program with my latest CURL Library and AmiSSL v5.
All it does is open up https://aminet.com front page and pipe it to CLI

Using #include <proto/amisslmaster.h>  // For OpenAmiSSLTags

and the following build command with Bebbo GGC 13.2
m68k-amigaos-gcc -O2 -D_POSIX_SOURCE -o tiny-browser tiny-browser.c -lcurl -l:libz.a  -lamisslauto -latomic -lc -lgcc -lm -msoft-float -mcrt=clib2

When building my test application I get the following undefined references
/opt/amiga13/lib/libcurl.a(libcurl_la-openssl.o): in function load_cacert_from_memory':
libcurl_la-openssl.o:(.text+0x62c4): undefined reference to X509_INFO_free'
/opt/amiga13/lib/libcurl.a(libcurl_la-openssl.o): in function cert_stuff':
libcurl_la-openssl.o:(.text+0x32d4): undefined reference to X509_free'

Stubbing them out in my program fixes the issue - program works with SSL and passes all tests
// Stub for X509_INFO_free
void X509_INFO_free(void *info) {
    // Dummy function: does nothing
    (void)info;
    return;
}
// Stub for X509_free
void X509_free(void *x) {
    // Dummy function: does nothing
    (void)x;
    return; 
}

Are these functions supposed to be in AmiSSL or somewhere else?
When compiling curl and zlib - no errors come up saying functions are broke / missing

Not a major issue as Stubbing them allows the application to work correctly.

Many Thanks,
Darren

**Comment by Futaura** [comment]
The functions are there, but these errors usually stem from passing them as a parameter to another function (not unusual in OpenSSL). You just need to add `-lamisslstubs` when linking and any required associated stubs will be linked in.

**Comment by boingball** [comment]
Thanks Futaura - 
Built with
m68k-amigaos-gcc -O2 -D_POSIX_SOURCE -o tiny-browser tiny-browser.c -lcurl -l:libz.a  -lamisslstubs  -lamisslauto -latomic -lc -lgcc -lm -msoft-float -mcrt=clib2
and it compiled fine without my stub's being in my program.

Apologies for this - much appreciated
